  only:
    - master

  cache:
    directories:
      - $HOME/.ivy2
      - $HOME/.sbt
      - $HOME/.m2/repository

    script:
      - sbt
        scalastyle
        test:scalastyle
        coverage test coverageReport coverageAggregate codacyCoverage
